-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 18:40:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `libreria` ;

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8 ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`libros` ;

CREATE TABLE IF NOT EXISTS `libreria`.`libros` (
  `id_libro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(35) NOT NULL,
  `stock` INT NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `pk_libros_UNIQUE` (`id_libro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`empleados` ;

CREATE TABLE IF NOT EXISTS `libreria`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `id_empleado_UNIQUE` (`id_empleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`ventas` ;

CREATE TABLE IF NOT EXISTS `libreria`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATE NOT NULL,
  `cantidad_libros` INT NOT NULL,
  `total_pagar` DECIMAL(7,2) NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_libro` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  UNIQUE INDEX `id_venta_UNIQUE` (`id_venta` ASC) VISIBLE,
  INDEX `fk_ventas_empleados_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_ventas_libros1_idx` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_empleados`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `libreria`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_libros1`
    FOREIGN KEY (`id_libro`)
    REFERENCES `libreria`.`libros` (`id_libro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libreria`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `libreria`.`usuarios` (
  `usuario` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `contrasenia` VARCHAR(30) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
